### ISSUE TITLE
possible to link to overlay data sources in readme?

### ISSUE THREAD

**Issue by derekeder** [ChicagoPublicSchools/Map-SchoolLocator#1]
The overlays outlined in the readme are great. Would it be possible to link to their data sources, either on the data portal or elsewhere?

Attendance Boundaries

```
Elementary School Attendance
Middle School Attendance
High School Attendance
Charter School Preference Boundary
```

Geographic Overlays

```
CPS Networks
Safe Passage Routes
CPS Tiers
Community Areas
Zip Codes
Transit
Bike Paths
```

Political Overlays

```
Wards
Illinois House District
Illinois Senate District
US Congressional District
```

**Comment by tedcanji** [comment]
Thanks for your suggestion - links to overlay data sources added.

**Comment by derekeder** [comment]
👍

**Comment by quhtani** [comment]
Dear Ted, could you send your email or twitter account plz. I need a little help if you don't mind.
ad2sms@hotmail.com

Thank you
